---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-ingress-controller
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami

