apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: workload-identity
  namespace: flux-system
spec:
  chart:
    spec:
      chart: workload-identity-webhook
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: workload-identity
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: workload-identity-system
  values:
    azureTenantID: 859e9d09-9fe3-4451-9029-35d7fb1f2e59
