apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: workload-identity
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://azure.github.io/azure-workload-identity/charts
