---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: keda
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keda
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: keda-system

