apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-sync
  namespace: runneragent
spec:
  provider: azure
  secretObjects:
  - secretName: github-auth
    type: Opaque
    data:
    - objectName: PAT
      key: PAT
    - objectName: ORGANISATION
      key: ORGANISATION
    - objectName: INGESTOR_REPOSITORY
      key: INGESTOR_REPOSITORY
    - objectName: API_REPOSITORY
      key: API_REPOSITORY
    - objectName: MGNT_REPOSITORY
      key: MGNT_REPOSITORY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "d32c56d3-c158-43a8-b600-72384cba3b88"
    keyvaultName: "orye-kv-ra-git"
    tenantId: "859e9d09-9fe3-4451-9029-35d7fb1f2e59"   
    objects:  |
        array:
          - |
            objectName: PAT
            objectType: secret 
          - |
            objectName: INGESTOR_REPOSITORY
            objectType: secret 
          - |
            objectName: API_REPOSITORY
            objectType: secret 
          - |
            objectName: MGNT_REPOSITORY
            objectType: secret 
          - |
            objectName: ORGANISATION
            objectType: secret