apiVersion: apps/v1
kind: Deployment
metadata:
  name: runneragent-deployment
  namespace: github-runners
  labels:
    app: github-runners
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-runners
  template:
    metadata:
      labels:
        app: github-runners
    spec:
      entrypoint: githubrunnerspool
      containers:
        - name: githubrunnerspool
          image: psxycrsharedacrstockdatamgnt.azurecr.io/environments/application/api:dev
          securityContext:
            privileged: true
            runAsUser: 0
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: ORGANISATION
              valueFrom:
                secretKeyRef:
                  name: azdo
                  key: github-runners-org
            - name: PAT
              valueFrom:
                secretKeyRef:
                  name: azdo
                  key: github-runners-pat
            - name: REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: azdo
                  key: github-runners-repo
          volumeMounts:
            - mountPath: /certs/client
              name: dind-certs
      sidecars:
        - name: dind
          image: 23.0.1-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          volumeMounts:
            - mountPath: /certs/client
              name: dind-certs
          readinessProbe:
            periodSeconds: 1
            exec:
              command: ["ls", "/certs/client/ca.pem"]
      volumes:
        - name: dind-certs
          emptyDir: {}
