name: Build and Deploy Management Landing Zone Resources
run-name: ${{ github.event.repository.updated_at}}_${{ github.run_number }}_${{ github.ref }}
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_ROOT_PATH: ${{ github.workspace }}/terraform
  ENVIRONMENT: fromJSON('["prd", "dev"]')[github.ref == 'refs/heads/main']
  TF_PLAN_FILE: terraform.tfplan
  TF_CONFIGURATIONS: '["management"]'
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          sed 's|"|"\|' $TF_CONFIGURATIONS >> $tf_configs
          echo "matrix={\"include\":$tf_configs}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - name: Build Terraform Configuration (Plan)
        uses: piroinno/stock-data-infra-tf-automation/build@init
        with:
          landingzonenamerootpath: ${{ env.TF_ROOT_PATH }}
          configurationfolder: ${{ github.action_path }}/configuration
          environment: ${{env.ENVIRONMENT }}
          terraformphase: plan
          automatedrun: true
          terraformconfigplanfilepath: ${{ github.workspace }}/terraform
          terraformconfigplanfile: ${{ env.TF_PLAN_FILE }}
          terraformworkingpath: ${{ env.RUNNER_TEMP }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Terraform  (Apply)
        uses: piroinno/stock-data-infra-tf-automation/build@init
        with:
          landingzonenamerootpath: ${{ github.workspace }}
          configurationfolder: ${{ github.action_path }}/configuration
          environment: ${{ github.event_name }}
          terraformphase: apply
          automatedrun: true
          terraformconfigplanfilepath: ${{ github.workspace }}/terraform
          terraformconfigplanfile: terraform.tfplan