name: Build and Deploy Management Landing Zone Resources
run-name: ${{ github.event.repository.updated_at}}_${{ github.run_number }}_${{ github.ref }}
on:
  workflow_dispatch:
    branches:
      - '**'
      # - dev
      # - main
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - dev
      - main
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  APP_LANDING_ZONE: 'management'
  APP_LANDING_ZONE_ROOT_PATH: ${{ github.workspace }}/application/management
  APP_NAMES: 'runneragent'
  APP_AUTO_WORKING_FOLDER: "./"
  APP_AUTO_WORKING_PATH: ${{ github.workspace }}/application
  #ENVIRONMENT: ${{ fromJSON('["dev", "prd"]')[github.ref == 'refs/heads/main'] }}
  ENVIRONMENT: mgnt

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        shell: pwsh
        run: |
          $matrix = @()
          $apps = "$($env:APP_NAMES)" -split ','
          foreach($app in $apps){
            $matrix += "{`"app`":`"$app`"}"
          }
          Write-Host("::set-output name=matrix::{`"include`":[$($matrix -join ',')]}")
          
  build:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        uses: piroinno/stock-data-infra-app-automation/build/docker/@init
        with:
          appfolder: ${{ matrix.app }}
          registryname: ${{ inputs.REGISTRY_NAME }}
          buildimagename: ${{ matrix.app }}
          tags: ${{ env.ENVIRONMENT }},latest
          pushimage: "true"
          dockerfile: "Dockerfile"
          dockerfileargs: "RUNNER_VERSION=2.303.0,RUNNER_TOKEN=${{ secrets.RUNNER_TOKEN }},ORGANISATION=${{ github.repository_owner }},REPOSITORY=${{ github.repository }}"
          acrloginserver: ${{ secrets.ACR_LOGIN_SERVER }}
          acrusename: ${{ secrets.ACR_USR_NAME }}
          acrpassword: ${{ secrets.ACR_PWD }}

  deploy:
    #if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest
    needs: [prepare,build,test]
    strategy:
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Terraform  (Apply)
        uses: piroinno/stock-data-infra-tf-automation/deploy@init
        with:
          configurationfolder: ${{ matrix.configuration }}
          terraformconfigplanfile: ${{ env.TF_PLAN_FILE }}_${{ matrix.configuration }}
          terraformphase: "apply"
          automatedrun: "true"